In [11]:
import pandas as pd

In [12]:
full_df = pd.read_csv("full_dataset.csv")[["uncertainty_expression", "llm_confidence_level", "annotater_confidence_score1", "annotater_confidence_score2", "annotater_confidence_score3", "annotater_confidence_score4", "annotater_confidence_score5"]]
filtered_df = pd.read_csv("linguistic_confidence_benchmark.csv")[["uncertainty_expression", "llm_confidence_level", "annotater_confidence_score1", "annotater_confidence_score2", "annotater_confidence_score3", "annotater_confidence_score4", "annotater_confidence_score5"]]

In [13]:
# Keep only full_df rows with matching uncertainty_expression in filtered_df
df = full_df[full_df["uncertainty_expression"].isin(filtered_df["uncertainty_expression"])].copy()
df

,uncertainty_expression,llm_confidence_level,annotater_confidence_score1,annotater_confidence_score2,annotater_confidence_score3,annotater_confidence_score4,annotater_confidence_score5
1,All signs point to Linus Pauling.,moderate,73,46,52,71,62
14,I believe Airrack hosted the 12th Streamy Awards.,moderate,75,79,53,67,37
35,The municipality seems to have been establishe...,moderate,75,40,56,77,70
46,It seems to me that Fatima Sydow was 50 years ...,moderate,79,63,52,73,40
54,The answer seems to be Pople.,moderate,65,72,54,64,24
...,...,...,...,...,...,...,...
9980,"As far as I know, the DOI is 10.1515/thli.2008...",moderate,64,73,69,63,65
9981,I’m fairly sure it happened in February 2008.,moderate,75,67,64,77,51
9984,I’m inclined to think that Aston Villa ended t...,moderate,71,63,65,81,63
9992,The engineer was probably British.,moderate,56,69,75,64,71
9996,"If memory serves, ""A Walk in Andante"" is the 1...",moderate,66,80,73,79,69

In [14]:
consolidated_df = df[["uncertainty_expression", "llm_confidence_level"]].copy()
consolidated_df["annotated_scores"] = df[["annotater_confidence_score1", "annotater_confidence_score2", "annotater_confidence_score3", "annotater_confidence_score4", "annotater_confidence_score5"]].values.tolist()
consolidated_df["annotated_scores"] = consolidated_df["annotated_scores"].apply(lambda x: [y / 100 for y in x if not pd.isna(y)])

In [15]:
consolidated_df.to_csv("annotated_confidence_data.pkl", index=True)

In [16]:
consolidated_df

,uncertainty_expression,llm_confidence_level,annotated_scores
1,All signs point to Linus Pauling.,moderate,"[0.73, 0.46, 0.52, 0.71, 0.62]"
14,I believe Airrack hosted the 12th Streamy Awards.,moderate,"[0.75, 0.79, 0.53, 0.67, 0.37]"
35,The municipality seems to have been establishe...,moderate,"[0.75, 0.4, 0.56, 0.77, 0.7]"
46,It seems to me that Fatima Sydow was 50 years ...,moderate,"[0.79, 0.63, 0.52, 0.73, 0.4]"
54,The answer seems to be Pople.,moderate,"[0.65, 0.72, 0.54, 0.64, 0.24]"
...,...,...,...
9980,"As far as I know, the DOI is 10.1515/thli.2008...",moderate,"[0.64, 0.73, 0.69, 0.63, 0.65]"
9981,I’m fairly sure it happened in February 2008.,moderate,"[0.75, 0.67, 0.64, 0.77, 0.51]"
9984,I’m inclined to think that Aston Villa ended t...,moderate,"[0.71, 0.63, 0.65, 0.81, 0.63]"
9992,The engineer was probably British.,moderate,"[0.56, 0.69, 0.75, 0.64, 0.71]"
9996,"If memory serves, ""A Walk in Andante"" is the 1...",moderate,"[0.66, 0.8, 0.73, 0.79, 0.69]"